### ISSUE TITLE
Add more information about yourself!

### ISSUE THREAD

**Issue by krishguptadev** [avneesh0612/avneesh0612#3]
Hey there,
I'd love to see more about you, like what are you learning, projects you are contributing to currently and more 😄

**Comment by avneesh0612** [comment]
Thanks, I will do it as soon as I get more content 😂

**Comment by avneesh0612** [comment]
Hey @krishguptadev I tried to add a bit more 🤣

**Comment by krishguptadev** [comment]
I mean like: 
![image](https://user-images.githubusercontent.com/91655303/143448582-5bad77f3-079a-4cfb-8c7e-b1063acde2a7.png)

**Comment by avneesh0612** [comment]
oh okay. Lemme get it from yours 🤓

**Comment by avneesh0612** [comment]
Does it now look better 👀

**Comment by krishguptadev** [comment]
Awesome a little para about you would be nice as well.

**Comment by avneesh0612** [comment]
I have no idea what else to add 😅😂

**Comment by krishguptadev** [comment]
np

**Comment by avneesh0612** [comment]
Thanks haha
